### ISSUE TITLE
Multi selections possible?

### ISSUE THREAD

**Issue by zhouhao27** [partho-maple/PBTreeView#2]
I've a few questions:

1. Do you support multiple selections?
2. Do you support node without child?

Thanks.

**Comment by partho-maple** [comment]
Hi, sorry for late reply. Been busy with other projects.

 1. No, multiple selection not supported at this moment. But will do in future. Updating this library for swift 4, will add support for this too.
 2. Yes, it does.

Thanks,
Partho.
